name: Linter

on:
  # Trigger the workflow on pull request targeting the main branch,
  # and run on push to branches currently under pull request
  pull_request_target:
    types:
      - opened
      - synchronize
    branches:
      - master
    paths:
      - dags/**

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ github.token }}
          auto_fix: false
          black: true
          black_dir: ./dags/
          black_args: --preview --skip-string-normalization
          black_auto_fix: false
          flake8: true
          flake8_dir: ./dags/
          flake8_args: --ignore=E501,W503,E203,F541,W291,W191,E101,E731,W605,W293
          flake8_auto_fix: false
