name: Pylint
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: '**/*.py'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # pip install -r requirements.txt

        
    - name: Analysing ${{ steps.changed-files.outputs.all_changed_files }} with pylint
      run: |
        pylint ${{ steps.changed-files.outputs.all_changed_files }}

